### ISSUE TITLE
下载apk会崩溃

### ISSUE THREAD

**Issue by 1843163412** [zhou-you/RxEasyHttp#125]

**Comment by 1843163412** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.MediaType.toString()' on a null object reference

**Comment by zhou-you** [comment]
请贴出详细的错误日志

**Comment by 1843163412** [comment]
01-09 09:32:19.828 11494-11494/? E/RxEasyHttp_:BaseSubscriber.onStart(L:48): -->http is onStart
01-09 09:32:19.851 11494-11501/? I/zygote64: Do partial code cache collection, code=61KB, data=38KB
    After code cache collection, code=61KB, data=38KB
    Increasing code cache capacity to 256KB
01-09 09:32:19.890 11494-11575/? D/RxEasyHttp_:DownloadSubscriber.onNext(L:87): DownSubscriber:>>>> onNext
01-09 09:32:19.890 32218-32256/? I/Market-DataParser: [InvalidPackageList] JSON : invalidSystemPackageList list is null
01-09 09:32:19.891 11494-11575/? W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.MediaType.toString()' on a null object reference
01-09 09:32:19.892 11494-11575/? W/System.err:     at com.zhouyou.http.subsciber.DownloadSubscriber.writeResponseBodyToDisk(DownloadSubscriber.java:93)
        at com.zhouyou.http.subsciber.DownloadSubscriber.onNext(DownloadSubscriber.java:88)
        at com.zhouyou.http.subsciber.DownloadSubscriber.onNext(DownloadSubscriber.java:43)
01-09 09:32:19.893 11494-11575/? W/System.err:     at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:108)
        at io.reactivex.internal.operators.observable.ObservableRetryWhen$RepeatWhenObserver.onNext(ObservableRetryWhen.java:100)
        at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onNext(ObservableOnErrorNext.java:68)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
01-09 09:32:19.894 11494-11575/? W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-09 09:32:19.895 11494-11575/? W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
01-09 09:32:19.898 3431-3467/? I/octvm_klo: klo lock

**Comment by zhou-you** [comment]
已去掉引起错误的日志打印，请用V2.1.4版本，但是你也要确认下MediaType为什么没有类型
