### ISSUE TITLE
The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.net.UnknownHostException: Unable to resolve host "www.mxnzp.com": No address associated with hostname at io.reactivex.processors.AsyncProcessor.b(AsyncProcessor.java:9)

### ISSUE THREAD

**Issue by zhousuqiang** [zhou-you/RxEasyHttp#207]
xx: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What&#39;s-different-in-2.0#error-handling | java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
	at co0.b(RxJavaPlugins.java:9)
	at fh0$a.onError(ObservableUnsubscribeOn.java:2)
	at ng0$a.onError(ObservableSubscribeOn.java:1)
	at rz.onError(BasicFuseableObserver.java:4)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onError(BodyObservable.java:2)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:13)
	at fw.subscribe(Observable.java:14)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:1)
	at fw.subscribe(Observable.java:14)
	at xe0.subscribeActual(ObservableMap.java:1)
	at fw.subscribe(Observable.java:14)
	at ng0$b.run(ObservableSubscribeOn.java:1)
	at nw$a.run(Scheduler.java:2)
	at xk0.run(ScheduledRunnable.java:2)
	at xk0.call(ScheduledRunnable.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
	at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:588)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:552)
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481)
	at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
	at wu0$b.read(Okio.java:4)
	at hu0$b.read(AsyncTimeout.java:2)
	at av0.a(RealBufferedSource.java:29)
	at av0.i(RealBufferedSource.java:1)
	at ws0.g(Http1Codec.java:1)
	at ws0.a(Http1Codec.java:34)
	at ls0.a(CallServerInterceptor.java:28)
	at qs0.a(RealInterceptorChain.java:13)
	at qs0.a(RealInterceptorChain.java:4)
	at ku.a(NoCacheInterceptor.java:3)
	at qs0.a(RealInterceptorChain.java:13)
	at ds0.a(ConnectInterceptor.java:7)
	at qs0.a(RealInterceptorChain.java:13)
	at qs0.a(RealInterceptorChain.java:4)
	at vr0.a(CacheInterceptor.java:22)
	at qs0.a(RealInterceptorChain.java:13)
	at qs0.a(RealInterceptorChain.java:4)
	at ks0.a(BridgeInterceptor.java:22)
	at qs0.a(RealInterceptorChain.java:13)
	at ts0.a(RetryAndFollowUpInterceptor.java:13)
	at qs0.a(RealInterceptorChain.java:13)
	at qs0.a(RealInterceptorChain.java:4)
	at ku.a(NoCacheInterceptor.java:3)
	at qs0.a(RealInterceptorChain.java:13)
	at qs0.a(RealInterceptorChain.java:4)
	at iu.a(HeadersInterceptor.java:6)
	at qs0.a(RealInterceptorChain.java:13)
	at qs0.a(RealInterceptorChain.java:4)
	at hr0.a(RealCall.java:28)
	at hr0.execute(RealCall.java:9)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:18)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:5)
	... 14 more
Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
	at libcore.io.Posix.recvfromBytes(Native Method)
	at libcore.io.Posix.recvfrom(Posix.java:189)
	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:549)
	... 49 more
java.net.SocketException: recvfrom failed: ECONNRESET (Connection reset by peer)
	at libcore.io.IoBridge.maybeThrowAfterRecvfrom(IoBridge.java:588)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:552)
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481)
	at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
	at wu0$b.read(Okio.java:4)
	at hu0$b.read(AsyncTimeout.java:2)
	at av0.a(RealBufferedSource.java:29)
	at av0.i(RealBufferedSource.java:1)
	at ws0.g(Http1Codec.java:1)
	at ws0.a(Http1Codec.java:34)
	at ls0.a(CallServerInterceptor.java:28)
	at qs0.a(RealInterceptorChain.java:13)
	at qs0.a(RealInterceptorChain.java:4)
	at ku.a(NoCacheInterceptor.java:3)
	at qs0.a(RealInterceptorChain.java:13)
	at ds0.a(ConnectInterceptor.java:7)
	at qs0.a(RealInterceptorChain.java:13)
	at qs0.a(RealInterceptorChain.java:4)
	at vr0.a(CacheInterceptor.java:22)
	at qs0.a(RealInterceptorChain.java:13)
	at qs0.a(RealInterceptorChain.java:4)
	at ks0.a(BridgeInterceptor.java:22)
	at qs0.a(RealInterceptorChain.java:13)
	at ts0.a(RetryAndFollowUpInterceptor.java:13)
	at qs0.a(RealInterceptorChain.java:13)
	at qs0.a(RealInterceptorChain.java:4)
	at ku.a(NoCacheInterceptor.java:3)
	at qs0.a(RealInterceptorChain.java:13)
	at qs0.a(RealInterceptorChain.java:4)
	at iu.a(HeadersInterceptor.java:6)
	at qs0.a(RealInterceptorChain.java:13)
	at qs0.a(RealInterceptorChain.java:4)
	at hr0.a(RealCall.java:28)
	at hr0.execute(RealCall.java:9)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:18)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:5)
	at fw.subscribe(Observable.java:14)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:1)
	at fw.subscribe(Observable.java:14)
	at xe0.subscribeActual(ObservableMap.java:1)
	at fw.subscribe(Observable.java:14)
	at ng0$b.run(ObservableSubscribeOn.java:1)
	at nw$a.run(Scheduler.java:2)
	at xk0.run(ScheduledRunnable.java:2)
	at xk0.call(ScheduledRunnable.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
	at libcore.io.Posix.recvfromBytes(Native Method)
	at libcore.io.Posix.recvfrom(Posix.java:189)
	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:549)
	... 49 more
android.system.ErrnoException: recvfrom failed: ECONNRESET (Connection reset by peer)
	at libcore.io.Posix.recvfromBytes(Native Method)
	at libcore.io.Posix.recvfrom(Posix.java:189)
	at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:549)
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481)
	at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
	at wu0$b.read(Okio.java:4)
	at hu0$b.read(AsyncTimeout.java:2)
	at av0.a(RealBufferedSource.java:29)
	at av0.i(RealBufferedSource.java:1)
	at ws0.g(Http1Codec.java:1)
	at ws0.a(Http1Codec.java:34)
	at ls0.a(CallServerInterceptor.java:28)
	at qs0.a(RealInterceptorChain.java:13)
	at qs0.a(RealInterceptorChain.java:4)
	at ku.a(NoCacheInterceptor.java:3)
	at qs0.a(RealInterceptorChain.java:13)
	at ds0.a(ConnectInterceptor.java:7)
	at qs0.a(RealInterceptorChain.java:13)
	at qs0.a(RealInterceptorChain.java:4)
	at vr0.a(CacheInterceptor.java:22)
	at qs0.a(RealInterceptorChain.java:13)
	at qs0.a(RealInterceptorChain.java:4)
	at ks0.a(BridgeInterceptor.java:22)
	at qs0.a(RealInterceptorChain.java:13)
	at ts0.a(RetryAndFollowUpInterceptor.java:13)
	at qs0.a(RealInterceptorChain.java:13)
	at qs0.a(RealInterceptorChain.java:4)
	at ku.a(NoCacheInterceptor.java:3)
	at qs0.a(RealInterceptorChain.java:13)
	at qs0.a(RealInterceptorChain.java:4)
	at iu.a(HeadersInterceptor.java:6)
	at qs0.a(RealInterceptorChain.java:13)
	at qs0.a(RealInterceptorChain.java:4)
	at hr0.a(RealCall.java:28)
	at hr0.execute(RealCall.java:9)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:18)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:5)
	at fw.subscribe(Observable.java:14)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:1)
	at fw.subscribe(Observable.java:14)
	at xe0.subscribeActual(ObservableMap.java:1)
	at fw.subscribe(Observable.java:14)
	at ng0$b.run(ObservableSubscribeOn.java:1)
	at nw$a.run(Scheduler.java:2)
	at xk0.run(ScheduledRunnable.java:2)
	at xk0.call(ScheduledRunnable.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by zhou-you** [comment]
根据异常是网络请求链接出问题了

**Comment by zhousuqiang** [comment]
好像是连接提示超时之类的，但是为什么出导致程序崩溃呢，希望您有时间能帮忙分析处理下，最近发现有些设备还是会出现这种情况。


原始邮件
发件人:周游notifications@github.com
收件人:zhou-you/RxEasyHttpRxEasyHttp@noreply.github.com
抄送:owenzhousuqiang@126.com; Authorauthor@noreply.github.com
发送时间:2020年2月20日(周四) 16:24
主题:Re: [zhou-you/RxEasyHttp] The exception could not be delivered to theconsumer because it has already canceled/disposed the flow or the exceptionhas nowhere to go to begin with. Further reading:https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling| java.net.UnknownHostException: Unable to resolve host "www.mxnzp.com": Noaddress associated with hostname atio.reactivex.processors.AsyncProcessor.b(AsyncProcessor.java:9) (#207)


根据异常是网络请求链接出问题了
