### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Base URL required. 	at retrofit2.Retrofit$Builder.build(Retrofit.java:575) 	at com.zhouyou.http.request.BaseRequest.build(BaseRequest.java:542)

### ISSUE THREAD

**Issue by LinYh08** [zhou-you/RxEasyHttp#248]
遇到Base URL required.问题

**Comment by LinYh08** [comment]
初始化的时候没有去设置baseUrl，等待进入页面的时候再进行  EasyHttp.getInstance().setBaseUrl设置，就会出现上面的问题吗？
