### ISSUE TITLE
java.net.SocketTimeoutException 网络连接超时，会导致应用闪退

### ISSUE THREAD

**Issue by littlezan** [zhou-you/RxEasyHttp#35]
我网络使用的代理，在我没有打开代理端(fiddler),打开应用，进行RxEasyHttp的post网络请求的时候，会出现上传，日志如下：

```
11-22 09:41:09.565 10049-10049/cn.ypp.telepathy E/EasyHttp:BaseSubscriber.onStart(L:48): -->http is onStart
11-22 09:41:09.574 10049-10049/cn.ypp.telepathy E/EasyHttp:BaseSubscriber.onStart(L:48): -->http is onStart
11-22 09:41:10.566 10049-10049/cn.ypp.telepathy E/EasyHttp:BaseSubscriber.onStart(L:48): -->http is onStart
11-22 09:41:22.134 10049-10049/cn.ypp.telepathy E/EasyHttp:BaseSubscriber.onError(L:69): -->http is onError
11-22 09:41:22.135 10049-10049/cn.ypp.telepathy E/EasyHttp:BaseSubscriber.onError(L:71): --> e instanceof ApiException err:com.zhouyou.http.exception.ApiException: 连接超时
11-22 09:41:22.137 10049-10049/cn.ypp.telepathy E/EasyHttp:BaseSubscriber.onError(L:69): -->http is onError
11-22 09:41:22.137 10049-10049/cn.ypp.telepathy E/EasyHttp:BaseSubscriber.onError(L:71): --> e instanceof ApiException err:com.zhouyou.http.exception.ApiException: 连接超时
11-22 09:41:22.180 10049-10049/cn.ypp.telepathy E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: cn.ypp.telepathy, PID: 10049
                                                                  java.net.SocketTimeoutException: failed to connect to /192.168.11.65 (port 8888) after 6000ms
                                                                      at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
                                                                      at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                      at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
                                                                      at java.net.Socket.connect(Socket.java:884)
                                                                      at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:63)
                                                                      at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:223)
                                                                      at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
                                                                      at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
                                                                      at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
                                                                      at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
                                                                      at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                      at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                      at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                      at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                      at com.zhouyou.http.interceptor.HeadersInterceptor.intercept(HeadersInterceptor.java:56)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                      at com.zhouyou.http.interceptor.CacheInterceptorOffline.intercept(CacheInterceptorOffline.java:86)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                      at com.zhouyou.http.interceptor.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:100)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                      at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                      at okhttp3.RealCall.execute(RealCall.java:69)
                                                                      at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
                                                                      at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
                                                                      at io.reactivex.Observable.subscribe(Observable.java:10903)
                                                                      at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
                                                                      at io.reactivex.Observable.subscribe(Observable.java:10903)
                                                                      at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
                                                                      at io.reactivex.Observable.subscribe(Observable.java:10903)
                                                                      at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
                                                                      at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
                                                                      at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                                                                      at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                                                                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoo

```

**Comment by zhou-you** [comment]
你好，你的问题解决了吗，我这边暂时没有发现这个问题呢，也有用过手机设置代理然后请求
