### ISSUE TITLE
有内存泄露的问题

### ISSUE THREAD

**Issue by dmh15454223** [zhou-you/RxEasyHttp#51]
StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                                               java.lang.Throwable: Explicit termination method 'close' not called
                                                                   at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                                   at java.io.FileOutputStream.<init>(FileOutputStream.java:222)
                                                                   at com.jakewharton.disklrucache.DiskLruCache.open(DiskLruCache.java:226)
                                                                   at http.cache.core.LruDiskCache.<init>(LruDiskCache.java:51)
                                                                   at http.cache.RxCache.<init>(RxCache.java:97)
                                                                   at http.cache.RxCache.<init>(RxCache.java:0)
                                                                   at http.cache.RxCache$Builder.build(RxCache.java:370)
                                                                   at http.request.BaseRequest.build(BaseRequest.java:522)
                                                                   at http.request.GetRequest.execute(GetRequest.java:82)
                                                                   at http.request.GetRequest.execute(GetRequest.java:77)
                                                                   at com.***.demo.activity.MainActivity.initData(MainActivity.java:114)
                                                                   at com.***.demo..framework.activity.BaseActivity.onCreate(BaseActivity.java:45)
                                                                   at com.***.demo.activity.MainActivity.onCreate(MainActivity.java:84)
                                                                   at android.app.Activity.performCreate(Activity.java:6864)
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)

**Comment by zhou-you** [comment]
请求很多的时候，退出页面可以取消请求
