### ISSUE TITLE
打包安装之后post请求崩溃

### ISSUE THREAD

**Issue by dingzhibing** [zhou-you/RxEasyHttp#76]
android studio直接运行到手机上没有问题，打包安装之后就崩溃，崩溃信息如下
java.lang.RuntimeException: loadStrategy(NO_CACHE) err!!com.zhouyou.http.c.d.NoStrategy
        at com.zhouyou.http.c.a.a(RxCache.java:241)
        at com.zhouyou.http.c.a.a(RxCache.java:113)
        at com.zhouyou.http.k.c.a(PostRequest.java:100)
        at com.zhouyou.http.k.c.a(PostRequest.java:83)
        at com.zhouyou.http.k.c.a(PostRequest.java:78)
        at com.huawei.hiqs.e.g.a(UserCenterPresenter.java:90)
        at com.huawei.hiqs.e.g.a(UserCenterPresenter.java:35)
        at com.huawei.hiqs.e.g$1.a(UserCenterPresenter.java:55)

EasyHttp.post("token")
                .cacheMode(CacheMode.NO_CACHE)
                .upJson(jsonObject.toString())
                .execute(new SimpleCallBack<TokenInfo>() {});

**Comment by dingzhibing** [comment]
EasyHttp.post("token")
                .cacheMode(CacheMode.CACHEANDREMOTE)
                .cacheKey("cachekey")
                .upJson(jsonObject.toString())
                .execute(new SimpleCallBack<TokenInfo>() {
换成CACHEANDREMOTE，还是报错

java.lang.RuntimeException: loadStrategy(CACHEANDREMOTE) err!!com.zhouyou.http.c.d.CacheAndRemoteStrategy
        at com.zhouyou.http.c.a.a(RxCache.java:241)
        at com.zhouyou.http.c.a.a(RxCache.java:113)
        at com.zhouyou.http.k.c.a(PostRequest.java:100)
        at com.zhouyou.http.k.c.a(PostRequest.java:83)
        at com.zhouyou.http.k.c.a(PostRequest.java:78)
        at com.huawei.hiqs.e.g.a(UserCenterPresenter.java:93)
        at com.huawei.hiqs.e.g.a(UserCenterPresenter.java:36)

**Comment by dingzhibing** [comment]
找到问题了，是我之前设置代码混淆的问题，不好意思
